package vo;
// Generated 17/02/2014 13:51:28 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Chavesativacao generated by hbm2java
 */
public class Chavesativacao  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


     private Integer id;
     private String versaoInstalada;
     private String chave;
     private String nome;
     private String email;
     private Integer usado;
     private Date dataAtivacao;

    /**
     *
     */
    public Chavesativacao() {
    }

    /**
     *
     * @param chave
     * @param nome
     * @param email
     */
    public Chavesativacao(String chave, String nome, String email) {
        this.chave = chave;
        this.nome = nome;
        this.email = email;
    }

    /**
     *
     * @param versaoInstalada
     * @param chave
     * @param nome
     * @param email
     * @param usado
     * @param dataAtivacao
     */
    public Chavesativacao(String versaoInstalada, String chave, String nome, String email, Integer usado, Date dataAtivacao) {
       this.versaoInstalada = versaoInstalada;
       this.chave = chave;
       this.nome = nome;
       this.email = email;
       this.usado = usado;
       this.dataAtivacao = dataAtivacao;
    }
   
    /**
     *
     * @return
     */
    public Integer getId() {
        return this.id;
    }
    
    /**
     *
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public String getVersaoInstalada() {
        return this.versaoInstalada;
    }
    
    /**
     *
     * @param versaoInstalada
     */
    public void setVersaoInstalada(String versaoInstalada) {
        this.versaoInstalada = versaoInstalada;
    }

    /**
     *
     * @return
     */
    public String getChave() {
        return this.chave;
    }
    
    /**
     *
     * @param chave
     */
    public void setChave(String chave) {
        this.chave = chave;
    }

    /**
     *
     * @return
     */
    public String getNome() {
        return this.nome;
    }
    
    /**
     *
     * @param nome
     */
    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     *
     * @return
     */
    public String getEmail() {
        return this.email;
    }
    
    /**
     *
     * @param email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     *
     * @return
     */
    public Integer getUsado() {
        return this.usado;
    }
    
    /**
     *
     * @param usado
     */
    public void setUsado(Integer usado) {
        this.usado = usado;
    }

    /**
     *
     * @return
     */
    public Date getDataAtivacao() {
        return this.dataAtivacao;
    }
    
    /**
     *
     * @param dataAtivacao
     */
    public void setDataAtivacao(Date dataAtivacao) {
        this.dataAtivacao = dataAtivacao;
    }




}


