package vo;
// Generated 17/02/2014 13:51:28 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Listaemail generated by hbm2java
 */
public class Listaemail  implements java.io.Serializable {
    private static final long serialVersionUID = 1L;


     private Integer codlista;
     private String nome;
     private Date data;
     private Set emails = new HashSet(0);

    /**
     *
     */
    public Listaemail() {
    }

    /**
     *
     * @param nome
     * @param data
     * @param emails
     */
    public Listaemail(String nome, Date data, Set emails) {
       this.nome = nome;
       this.data = data;
       this.emails = emails;
    }
   
    /**
     *
     * @return
     */
    public Integer getCodlista() {
        return this.codlista;
    }
    
    /**
     *
     * @param codlista
     */
    public void setCodlista(Integer codlista) {
        this.codlista = codlista;
    }

    /**
     *
     * @return
     */
    public String getNome() {
        return this.nome;
    }
    
    /**
     *
     * @param nome
     */
    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     *
     * @return
     */
    public Date getData() {
        return this.data;
    }
    
    /**
     *
     * @param data
     */
    public void setData(Date data) {
        this.data = data;
    }

    /**
     *
     * @return
     */
    public Set getEmails() {
        return this.emails;
    }
    
    /**
     *
     * @param emails
     */
    public void setEmails(Set emails) {
        this.emails = emails;
    }




}


